### ISSUE TITLE
update CI

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaUtilities.jl#10]
Even though merge queue will run our CI twice, I think it's worth it since our CI only contains unit tests, which are quick to run.

Edit 13 Nov 2023: Since this is a low-commit repo, we don't need to use merge queue, instead we can update our github actions workflows to run the entire CI pipeline for each commit, as was done [here](https://github.com/CliMA/ClimaLSM.jl/pull/374/files) in ClimaLSM.

**Comment by juliasloan25** [comment]
Charlie's guide to switch from bors to merge queue: https://github.com/CliMA/policies/wiki/Migrating-from-Bors-to-GitHub-Merge-Queue

**Comment by Sbozzolo** [comment]
CI no longer uses bors and doesn't need any update, so I am closing this.
