### ISSUE TITLE
improve docs

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaUtilities.jl#11]
We should improve our docs, with more pages and categories, and a filled-out `docs/src/index.md` page. We can follow ClimaCoupler.jl as a template.

- coupler pages layout: https://github.com/CliMA/ClimaCoupler.jl/blob/main/docs/make.jl#L54-L76
- coupler index.md page: https://github.com/CliMA/ClimaCoupler.jl/blob/main/docs/src/index.md

**Comment by Sbozzolo** [comment]
I think we have pretty good docs now, maybe we can close this?
