### ISSUE TITLE
Fix imports

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaUtilities.jl#48]
We probably shouldn't import CUDA/adapt in this way: `import ClimaCore.Fields: Adapt, CUDA`

Found in this build (when moving CUDA to an extension in ClimaCore): https://buildkite.com/clima/climaatmos-ci/builds/18491#018f108f-a28b-464d-9008-d81246d5e9a3

**Comment by Sbozzolo** [comment]
The reason we import them this way is to avoid adding dependencies to ClimaUtilities.

But yes, we need to change it if the assumption that Adapt/CUDA cannot be obtained from ClimaCore is no longer valid.
